app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('user/', include('user.urls')),
    path('', views.IndexMain.as_view()), 
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # path(패턴, 매핑) /blog/
    # path("", views.index), # FBV
    path("", views.Index.as_view(), name='list'),
    # 글 조회
    path("detail/<int:pk>/", views.DetailView.as_view(), name='detail'),
    # 글 작성
    path("write/", views.WriteView.as_view(), name='write'),
    # 글 수정
    path("edit/<int:pk>/", views.EditView.as_view(), name='edit'),
    # 글 삭제
    path("delete/<int:pk>/", views.Delete.as_view(), name='delete'),
    # 글 검색
    path("search/<str:tag>/", views.PostSearch.as_view(), name='search'),
    # 코멘트 작성
    path("<int:pk>/comment/write/", views.CommentWrite.as_view(), name="cm-write"),
    # 코멘트 수정
    path("comment/update/<int:pk>/", views.CommentWrite.as_view(), name="cm-update"),
    # 코멘트 삭제
    path("delete/<int:pk>/comment/delete/", views.CommentDelete.as_view(), name="cm-delete")
]

blog/models.py
from django.db import models
# from django.contrib.auth import get_user_model

# User = get_user_model()

# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    writer = models.ForeignKey('user.User', on_delete=models.CASCADE ,max_length=20)
    category = models.ForeignKey('Category', null=True, blank=True, on_delete=models.SET_NULL)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'[{self.pk}]{self.title} :: {self.author}'

    def get_absolute_url(self):
        return f'/blog/{self.pk}/'




class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField()
    writer = models.ForeignKey('user.User', on_delete=models.CASCADE ,max_length=20)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'[{self.content}] {self.content} :: {self.writer}'
    
    def get_absolute_url(self):
        return f'/blog/{self.post.pk}/#comment-{self.pk}'
    
    class Meta:
        ordering = ['-id']
    


class Category(models.Model):
    name = models.CharField(max_length=25, unique=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True, allow_unicode = True)
    is_public = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return f'/blog/category/{self.slug}'
    
    class Meta:
        verbose_name_plural = 'Categories'

blog/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['title', 'content', 'category']


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['content']
        widgets = {
            'content': forms.Textarea(attrs={'rows' : '3', 'cols' : '30'})
        }

blog/views.py
# from typing import Any
# from django import http
# from django.forms.models import BaseModelForm
from django.http.response import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist, ValidationError
from django.http import HttpResponse
from django.views.generic import View, UpdateView
from .models import Post, Comment, Category
from .forms import PostForm, CommentForm



###Post
class Index(View):
    def get(self, request):
        posts = Post.objects.all()
        context = {
            "posts" : posts,
            "title" : "Blog"
        }
        return render(request, "blog/post_list.html", context)
    

class WriteView(LoginRequiredMixin,View):
    def get(self, request):
        form = PostForm()
        context = {
            "form": form,
            "title": "Blog"
        }
        return render(request, "blog/post_form.html", context)
    
    def post(self, request):
        form = PostForm(request.POST)

        if form.is_valid():
            post = form.save(commit=False)
            post.writer = request.user
            post.save()
            return redirect("blog:list")
        
        context = {
            'form': form
        }

        return render(request, "blog/post_form.html", context)


class DetailView(View):

    def get(self, request, pk):
        post = Post.objects.prefetch_related('comment_set').get(pk=pk)
        comments = post.comment_set.all()
        comment_form = CommentForm()

        context = {
            "title" : "Blog",
            "post_id" : pk,
            "post_title" : post.title,
            "post_writer" : post.writer,
            "post_content" : post.content,
            "post_category" : post.category,
            "post_created_at" : post.created_at,
            "comments" : comments,
            "comment_form" : comment_form,
        }
        return render(request, 'blog/post_detail.html', context)
    

class EditView(View):
    def get(self, request, pk):
        post = get_object_or_404(Post, pk=pk)
        form = PostForm(initial={'title' : post.title, 'content' : post.content, 'category' : post.category})

        context = {
            'form' : form,
            'post' : post,
            'title' : 'Blog' 
        }
        return render(request, 'blog/post_edit.html', context)

    def post(self, request, pk):
        post = get_object_or_404(Post, pk=pk)
        form = PostForm(request.POST)

        if form.is_valid():
            post.title = form.cleaned_data['title']
            post.content = form.cleaned_data['content']
            post.category = form.cleaned_data['category']
            post.save()
            return redirect('blog:detail', pk=pk )

        context = {
            'form' : form,
            'post' : post,
            'title' : 'Blog'
        } 
        
        return render(request, 'blog/post_edit.html', context)
    

class Delete(View):
    def post(self, request, pk):
        post = get_object_or_404(Post,pk=pk)
        post.delete()
        return redirect('blog:list')


# class SearchView(View):
#     def post(self, request):
#         if request.method == 'POST':
#             searched = request.POST['searched']  
#             posts = Post.objects.filter(title__contains=searched) or Post.objects.filter(writer__contains=searched) or Post.objects.filter(category__contains=searched)
#             return render(request, 'blog/post_search.html', {'searched': searched, 'posts': posts})
#         else:
#             return render(request, 'blog/post_search.html', {})


#나중에 검색 기능 추가하기#
class PostSearch(View):
    def get(self, request, tag):
        print(f'request.GET: {request.GET}')
        post_objs = Post.objects.filter(category=tag)
        print(f'tag: {tag}')
        context = {
            'title': 'Main Page',
            'posts': post_objs,
        }
        return render(request, 'blog/post_list.html', context)
    


###Comment
class CommentWrite(LoginRequiredMixin, View):
    def post(self, request, pk):
        form = CommentForm(request.POST)
        post = get_object_or_404(Post, pk=pk)

        if form.is_valid():
            content = form.cleaned_data['content']
            writer = request.user

            try:
                comment = Comment.objects.create(post=post, content=content, writer=writer)
            except ObjectDoesNotExist as e:
                print('게시물이 존재하지 않습니다.', str(e))
            except ValidationError as e:
                print('오류가 발생했습니다.', str(e))
            return redirect('blog:detail', pk=pk)
        
        context = {
            'title':'Blog',
            'post_id':pk,
            'comments':post.comment_set.all(),
            'comment_form':form
        }
        return render(request, 'blog/post_detail.html', context)
    

class CommentDelete(View):
    def post(self, request, pk):
        if request.user.is_authenticated:
            comment = get_object_or_404(Comment, pk=pk)
            post_id = comment.post.id
            if comment.writer == request.user:
                comment.delete()
                return redirect(comment.post.get_absolute_url())
            else:
                return HttpResponse('You are not allowed to delete this comment')
        return redirect('/blog/')
    


class CommentUpdate(LoginRequiredMixin, UpdateView):
    model = Comment
    form = CommentForm

    def form_valid(self, form):
        current_user = self.request.user
        if current_user.is_authenticated:
            form.instance.writer = current_user
            return super(CommentUpdate, self).form_valid(form)
        else:
            return redirect('/blog/')
        
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            comment = self.get_object()
            if comment.writer == request.user:
                return super().dispatch(request, *args, **kwargs)
            else:
                return HttpResponse('You are not allowed to update this comment')
        return super().dispatch(request, *args, **kwargs)



###Category
def category_page(request, slug):
    category = Category.objects.get(slug=slug)
    categories = Category.objects.all().order_by('-name')
    context = {
        'post_list': Post.objects.filter(category=category).order_by('-pk'),
        'categories': categories,
        'no_category_post_count': Post.objects.filter(category=None).count(),
        'category': category,
        'category_list': Category.objects.all().order_by('-name'),
    }
    return render(request, 'blog/post_list.html', context)

blog/templates/blog/form_error.html
<div class="alret alret-danger">
    {{ form }}
</div>

blog/templates/blog/post_detail.html
{% extends 'base.html' %}

{% block content %}
<hr>
    <h2>Title: {{ post_title }}</h2>
    {% if post_writer == request.user %}
        <a href="{% url 'blog:edit' pk=post_id %}" class="btn">Edit</a>
        <form action="{% url 'blog:delete' pk=post_id %}" method="post">
            {% csrf_token %}
            <input type="submit" value="Delete" class="btn">
        </form>
    {% endif %}

    <!-- {% if post.writer == request.user %}
        <a href=""></a> 
        {% endif %}-->
    <p>Writer: {{ post_writer }}</p>
    <p>Content: {{ post_content }}</p>
    <p>Category: {{ post_category }}</p>
    <p>Date: {{ post_created_at }}</p>
    <hr>

    <h3>Comment</h3>
    <form action="{% url 'blog:cm-write' pk=post_id %}" method="post">
        {% csrf_token %}
        {% if comment_form.errors %}
            {% with form=comment_form %}
                {% include 'blog/form_error.html' %}
            {% endwith %}
        {% else %}
            {{ comment_form.content }}
        {% endif %}
        <input type="submit" value="Submit">
    </form>
    <br>

    {% if comments %}
        <ul>
            {% for comment in comments %}
                <li>{{ comment.content}} - {{ comment.writer }} / {{ comment.created_at}}
                    {% if comment.writer == request.user %}
                        <form action="{% url 'blog:cm-delete' pk=comment.pk %}" method="post">
                            {% csrf_token %}
                            <input type="submit" value="✗" class="btn">
                        </form>
                    {% endif %}
                </li>
            {% endfor%}
        </ul>
    {% else %}
        <p>댓글이 없습니다.</p>
    {% endif %}
{% endblock %}

blog/templates/blog/post_edit.html
{% extends "base.html" %}

{% block content %}
<hr>
    <form action="{% url 'blog:edit' pk=post.pk %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Edit">
    </form>
{% endblock  %}

blog/templates/blog/post_form.html
{% extends 'base.html' %}

{% block content %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!-- Toast Editor 2.0.0과 의존성 -->
    <link
        rel="stylesheet"
        href="https://uicdn.toast.com/editor/latest/toastui-editor.min.css"
    />
    <script src="https://uicdn.toast.com/editor/latest/toastui-editor-all.min.js"></script>
</head>
<body>
    <hr>
    <h1>블로그 글 작성 화면</h1>
    <!-- <form action="{% url 'blog:write' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-outline-success" value="Submit">
    </form> -->
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table class="table">
            {{form}}
            <!-- <tr>
                <th><label for="id_tags">Tags:</label></th>
                <td><input type="text" name="tags_str" id="id_tags_str"></td>
            </tr> -->
            <!-- <tr>
                <th><label for="id_content_editor">Content_editor:</label></th>
                <td><div id="editor"></div></td>
            </tr> -->
        </table>
        <button type="submit" id="submitbtn">완료</button>
        <!-- <a href="{% url 'blog:list' %}" class="btn">나가기</a> 이 부분은 나중에 화살표 이모티콘으로 대체할 예정-->
    </form>
    <script>
        // const Editor = toastui.Editor;

        // const editor = new Editor({
        //     el: document.querySelector("#editor"),
        //     height: "600px",
        //     initialEditType: "markdown",
        //     previewStyle: "vertical",
        // });

        // // editor.getHTML()
        // // editor.getMarkdown()
        // document.getElementById('submitbtn').addEventListener('click', function(){
        //     const markdownContent = editor.getMarkdown();
        //     document.getElementById('id_content').value = markdownContent;
        // });
    </script>
</body>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'base.html' %}

{% block content %}
<hr>
    {% if user.is_authenticated %}
        <h1>Board</h1>
        <form action="{% url 'blog:write' %}" class="btn">
            <input type="submit" value="Write">
        </form>
        <input type="text" name="q" id="search-input">
        <button id="search-btn">Search</button>
        <form action="{% url 'blog:list' %}" class="btn">
            <input type="submit" value="⟳">
        </form>
        <form  id="search-form" action="{% url 'blog:search' tag='value' %}" method="get">
            {% csrf_token %} 
            카테고리 검색 : <input id="search-input" type="text" placeholder="검색어를 입력하세요."/>   
            <input type="submit" value="Search">
        </form> 
        
        <!-- 글이 있을 때 -->
        <!-- 테이블 -->
        <main id="main">
            {% if posts %}
                <table class="table ">
                    <thead>
                        <tr>
                        <th scope="col">No.</th>
                        <th scope="col">Title</th>
                        <th scope="col">Content</th>
                        <th scope="col">Category</th>
                        <th scope="col">Writer</th>
                        <th scope="col">Create Date</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for post in posts %}
                            <tr>
                                <th scope="row">{{ post.pk }}</th>
                                <td><a href="{% url 'blog:detail' pk=post.pk %}">{{ post.title }}</a></td>
                                <td>{{ post.content | truncatewords:45 }}</td>
                                <td>{{ post.category }}</td>
                                <td>{{ post.writer }}</td>
                                <td>{{ post.created_at }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
            <!-- 글이 없을 때 -->
            <!-- 글이 없습니다. -->
                <p>작성된 게시물이 없습니다.</p>
            {% endif %}
        </main>
        <aside>
            <h2>Category</h2>
            <ul>
                {% for category in category_list %}
                <li><a href="{{ category.get_absolute_url }}">{{ category.name }} {{ category.post_set.count }}</a></li>
                {% endfor %}
            </ul>
        </aside>
        <script>
            const form = document.querySelector('#search-form')
            const input = document.querySelector('#search-input')
            input.addEventListener('input', () => {
                inputValue = input.value
                s = `{% url 'blog:search' tag="value" %}`
                console.log(s)
                s = s.replace('value', inputValue)
                console.log(s)
                form.action = s
            });
            document.querySelector('#search-btn').addEventListener('click', () => {
                const searchInput = document.querySelector('#search-input');
                const searchValue = searchInput.value;
                location.href = `/blog/?q=${searchValue}`;
            });
        </script>
    {% else %}
        <p>로그인 후 이용해주세요.</p> 
    {% endif %}
{% endblock %}

blog/templates/blog/post_search.html
{% extends "base.html" %}

{% block content %}
<hr>
    {% if post_objs %}
        <h1> 검색하신 {{ post_obj }} 입니다. </h1>
        <table class="table table-bordered">
            <thead class="table-light">
                <tr>
                    <td>제목</td>
                    <td>작성자</td>
                    <td>카테고리</td>
                    <td>작성시간</td>
                </tr>
            </thead>
            <tbody>
                {% for post in posts %}
                    <tr>
                        <td><a href="{% url 'blog:detail' pk=post.pk %}" class="btn">{{ post.title }}</a></td>
                        <td>{{ post.writer }}</td>
                        <td>{{ post.category }}</td>
                        <td>{{ post.created_at }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %} 
    <!-- 글이 없을 때 -->
    <!-- 글이 없습니다. -->
        <p>검색된 게시물이 없습니다.</p>
    {% endif %}
{% endblock  %}