app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('user/', include('user.urls')),
    path('', views.IndexMain.as_view()), 
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # path(패턴, 매핑) /blog/
    # path("", views.index), # FBV
    path("", views.Index.as_view(), name='list'),
    # 글 조회
    path("detail/<int:pk>/", views.DetailView.as_view(), name='detail'),
    # 글 작성
    path("write/", views.WriteView.as_view(), name='write'),
    # 글 수정
    path("edit/<int:pk>/", views.EditView.as_view(), name='edit'),
    # 글 삭제
    path("delete/<int:pk>/", views.Delete.as_view(), name='delete'),
    # 글 검색
    path("search/<str:tag>/", views.PostSearch.as_view(), name='search'),
    # 코멘트 작성
    path("<int:pk>/comment/write/", views.CommentWrite.as_view(), name="cm-write"),
    # 코멘트 수정
    path("comment/update/<int:pk>/", views.CommentWrite.as_view(), name="cm-update"),
    # 코멘트 삭제
    path("delete/<int:pk>/comment/delete/", views.CommentDelete.as_view(), name="cm-delete")
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns=[
    path('join/', views.Join.as_view(), name='join'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
]

templates/base.html
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
        <title>
            {% block title %} {{ title }} {% endblock %}
        </title>

    {% bootstrap_css %}
    {% bootstrap_javascript %}
    </head>
    <body>
        <div class="container">
                <nav>
                    <ul>
                        {% if user.is_authenticated %}
                            <li><p>Welcome! {{ user.email }}</p></li>
                            <li><a href="{% url 'user:logout' %}">Logout</a></li>
                        {% else %}
                            <li><p>Please, Login</p></li>
                            <li><a href="{% url 'user:login' %}">Login</a></li>
                        {% endif %}
                        <li><a href="http://127.0.0.1:8000">Home</a></li>
                        <li><a href="{% url 'blog:list' %}">Board</a></li>
                        <li><a href="#">About</a></li>
                    </ul>
                </nav>
            {% block content %}
            
            {% endblock  %}
        </div>
    </body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <title>{% block title %} {{ title }} {% endblock %}</title>
    <link rel="stylesheet" href="./css/index.css">
</head>
{% block content %}
    <div class="main-container">
        <h2>음악 추천 블로그</h2>
        <h2>Welcome!</h2>
        <a href="{% url 'user:join' %}" class="btn">Join</a>
        <a href="{% url 'user:login' %}" class="btn">Login</a>
        <a href="{% url 'blog:list' %}" class="btn">Board</a>
    </div>
{% endblock %}